sudo: required
language: generic
dist: focal

services:
- docker

matrix:
  include:
  - name: Bionic melodic
    env: ROS_DISTRO=melodic
  - name: Bionic melodic_llvm
    env: ROS_DISTRO=melodic_llvm
  - name: Focal Fossa noetic
    env: ROS_DISTRO=noetic
  - name: Focal Fossa noetic_llvm
    env: ROS_DISTRO=noetic_llvm

script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin || true
  - docker build -f ./docker/$ROS_DISTRO/Dockerfile .

env:
  global:
  - secure: xMQFPf2nogRIc7wn6/aHq7B5++gf1aMQggL2R+xfL5rayCRNPgYZrIvZTS8sIey7aatxM3nWGd3YuTbFQpiNU4W8+8s1RiFvxrARFa9KpW5uPXno48dbxyTFKIrhFqw7QWI412r5UwznfblYl47UUsjXnj8v6E8okVR47JYe1WNu6LfSNm59sD4GMv96YAq6eV2ZFb+M4cO3d2uBDe8An8GQeVZJjsXV57i75QVOKze/7+nLgikmOXUUaWHOZRlbXhaz0JbiIX+Canqeq3tBxLTDkNfYAkAfCAeyf1RpsJLnsegV3m79fqoyOPaFgnUSa+75g6W4zJ1TH8SpmfrLv2xZTZ621ljV9h4mRYIiJpc6YAxYm6fk9M4b1w0irm+kpI8AmJcs74hQtB28sUUNdLOp2r41yAITfE24k+QZ/PoftYdQgyeRf7WEHJLYYxbUIzkfVfiBmVbkeLZJGY5251AOuIHWjkVc6Z/yMSU2aAY1Wue1cqbqpWsnPclgvHgDKhq3dVY6H9rCIPgTZiztp43ZpzuEWY4LxJxrJKX3ZGNAzIVwka1uSXbu4W9x7HAoyA4dqtG+FGC9Jm+yRLSHo4lIkTFBANzuSt5z0NxNCwaml4OO9lApZ1AIn3cKhHUXG/u+CGhVSEvQuHYTpL2tMxRuxiUVD0cxmy48fttnGUA=
  - secure: QlqYV2mR30pjTLSSfg+Px+fYl8jPRSD4cBssIk/m9ATTG8ewXrtnfAvVfmlhNWEwXRO4ZPM/unNNbZf4CxGmJs6zgTK5wonyoIjOjghEPMdYYPsGxNO2Avw+q/7DL/DwLAbjDZN3Cdx+zj86Ufh2RwKzdJ9K2JbyluWSU3dsXYX9V1tbntk5nUgya0MQbpO9min42PeqG1oBBsD7n2F/X7iVBtE0nxvRg8jBmX/QlBNIO9qLip/3m/arUUGa95Nb8dNR85H+kIlgQQ2K94aWXbLHgoznnPYBpOfCSvnY4fZXNH8e64kC8kuCC0LnDnpk5aWMKqJZZll2kqmkg1Acaz1hgwzxdzpyX1ssrTFsmCZR9vJq3063veXOHAZItTTD59UKiS0beolf087l3kU8JsWjaLKho7vXGDtTBtWDUWaUSksR/+NU7/sciLhomiZRWJzEi+3uiAfHyT2kLQZO57f9LH3sMMOVh3zUPnMESkp7ewMK4lEjjOXYasDEehMLVaoSvwr8Fh/ZbqvzvECgDh5vD54zjdfHLhjkRB9eITWZWYJyKeSMqFpTFnZvZEH8bdMwh40XMe1Zqd/3ZRClKv4TIAg0W5GMQ/bE8HfVoTZj8TIOYgmyt01+ka9imzu+A7YV77Wui2wzNg/y/4w69bd84PLVt7gtEZ3oz8Kddms=
